logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/storerx
    username: postgres
    password: 123
